### ISSUE TITLE
Configuration options

### ISSUE THREAD

**Issue by arax** [CESNET/itchy#2]
Can you, please, clarify what the following options (marked with `# <<< ??`) do? Maybe provide a few examples of data placed in those directories by itchy?
```yml
  metadata_dir: /var/spool/onevmcatcher  # <<< ??
  template_dir:                          # <<< ??
  output_dir:                            # <<< ??
  descriptor_dir: /vmcatcher/descriptors # <<< ??
  log_to: stderr
  log_level: error
  ca_path: /etc/grid-security/certificates
  ca_file:
  debug: false
  skip_ca_check: false                   # <<< ??
```
